export { MenuContentPage } from './menu-content.page'
export { ProductList } from './product-list.page'
export { Login } from './login.page'
export { AddressStep } from './address-step.page'
export { ShippingStep } from './shipping-step.page'
export { PaymentStep } from './payment-step.page'
export { ShoppingCart } from './shopping-cart.page'
export { DressesListPage } from './dresses-list.page'
